# Generated by Django 5.2.7 on 2025-10-29 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('person_id', models.CharField(blank=True, max_length=128, null=True)),
                ('emotion', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='emotion_events/')),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
