# Generated by Django 5.2.7 on 2025-10-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotiondetectionevent',
            name='image',
        ),
    ]
