# Generated by Django 4.2 on 2025-10-15 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la configuration')),
                ('camera_index', models.IntegerField(default=0, verbose_name='Index de la caméra')),
                ('enable_motion_detection', models.BooleanField(default=True, verbose_name='Activer détection de mouvement')),
                ('enable_face_detection', models.BooleanField(default=True, verbose_name='Activer détection de visages')),
                ('motion_threshold', models.IntegerField(default=25, verbose_name='Seuil de mouvement')),
                ('min_contour_area', models.IntegerField(default=500, verbose_name='Surface minimale du contour')),
                ('save_images', models.BooleanField(default=True, verbose_name='Sauvegarder les images')),
                ('detection_interval', models.IntegerField(default=1, verbose_name='Intervalle de détection (secondes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Configuration active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Paramètre de caméra',
                'verbose_name_plural': 'Paramètres de caméra',
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(choices=[('motion', 'Détection de Mouvement'), ('face', 'Détection de Visage'), ('both', 'Mouvement et Visage')], default='motion', max_length=10, verbose_name='Type de détection')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='detections/%Y/%m/%d/', verbose_name='Image capturée')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Niveau de confiance')),
                ('faces_count', models.IntegerField(default=0, verbose_name='Nombre de visages détectés')),
                ('motion_intensity', models.FloatField(default=0.0, verbose_name='Intensité du mouvement')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localisation (optionnel)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Événement de détection',
                'verbose_name_plural': 'Événements de détection',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='detectionevent',
            index=models.Index(fields=['-timestamp'], name='detection_d_timesta_bff5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionevent',
            index=models.Index(fields=['detection_type'], name='detection_d_detecti_dc4314_idx'),
        ),
    ]
