# Generated by Django 5.2.7 on 2025-10-29 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='detections/original/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='detections/annotated/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('objects_detected', models.IntegerField(default=0)),
                ('detection_data', models.TextField(blank=True, help_text='JSON string with detection details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
