# Generated by Django 5.2.7 on 2025-10-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='description',
            field=models.TextField(blank=True, help_text='Description or notes about this detection'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='location',
            field=models.CharField(blank=True, help_text='Location where image was captured', max_length=200),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'security, entrance, daytime')", max_length=500),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='title',
            field=models.CharField(blank=True, help_text='Custom title for this detection', max_length=200),
        ),
    ]
