# Generated by Django 5.2.7 on 2025-10-29 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern Recognition'), ('prediction', 'Predictive Insight'), ('recommendation', 'Recommendation'), ('summary', 'Summary')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('data', models.TextField(default='{}', help_text='JSON: supporting data')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Insight',
                'verbose_name_plural': 'Analytics Insights',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_detections', models.IntegerField(default=0)),
                ('total_objects_detected', models.IntegerField(default=0)),
                ('avg_objects_per_detection', models.FloatField(default=0.0)),
                ('objects_by_class', models.TextField(default='{}', help_text='JSON: object classes and their counts')),
                ('detections_by_hour', models.TextField(default='{}', help_text='JSON: detections per hour')),
                ('suspicious_objects_count', models.IntegerField(default=0)),
                ('high_risk_detections', models.IntegerField(default=0, help_text='Detections with high-risk objects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Analytics',
                'verbose_name_plural': 'Detection Analytics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user', 'period_type', 'period_start'], name='analytics_d_user_id_893dab_idx'), models.Index(fields=['period_start', 'period_end'], name='analytics_d_period__513603_idx')],
                'unique_together': {('user', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='ObjectTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(db_index=True, max_length=100)),
                ('detection_count', models.IntegerField(default=0)),
                ('first_detected', models.DateTimeField()),
                ('last_detected', models.DateTimeField()),
                ('trend_direction', models.CharField(choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('decreasing', 'Decreasing')], default='stable', max_length=20)),
                ('is_anomaly', models.BooleanField(default=False, help_text='Unusual detection pattern')),
                ('anomaly_score', models.FloatField(default=0.0, help_text='Anomaly severity (0-1)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object Trend',
                'verbose_name_plural': 'Object Trends',
                'ordering': ['-detection_count', '-last_detected'],
                'indexes': [models.Index(fields=['user', 'object_class'], name='analytics_o_user_id_b57239_idx'), models.Index(fields=['is_anomaly', 'anomaly_score'], name='analytics_o_is_anom_85a68d_idx')],
                'unique_together': {('user', 'object_class')},
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('suspicious_object', 'Suspicious Object'), ('anomaly', 'Anomaly Detected'), ('trend_change', 'Trend Change'), ('high_frequency', 'High Frequency Detection'), ('unusual_time', 'Unusual Time Detection')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('context_data', models.TextField(default='{}', help_text='JSON: additional context')),
                ('is_read', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detection.detectionresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Alert',
                'verbose_name_plural': 'Security Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'severity'], name='analytics_s_user_id_650661_idx'), models.Index(fields=['created_at', 'severity'], name='analytics_s_created_b1471d_idx')],
            },
        ),
    ]
