# Generated by Django 5.2.7 on 2025-10-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionanalytics',
            name='anomaly_count',
            field=models.IntegerField(default=0, help_text='Number of anomalies detected'),
        ),
        migrations.AddField(
            model_name='detectionanalytics',
            name='avg_confidence',
            field=models.FloatField(default=0.0, help_text='Average detection confidence'),
        ),
        migrations.AddField(
            model_name='detectionanalytics',
            name='detections_by_weekday',
            field=models.TextField(default='{}', help_text='JSON: detections by day of week'),
        ),
        migrations.AddField(
            model_name='detectionanalytics',
            name='peak_detection_count',
            field=models.IntegerField(default=0, help_text='Max detections in a single hour'),
        ),
        migrations.AddField(
            model_name='detectionanalytics',
            name='peak_detection_hour',
            field=models.IntegerField(blank=True, help_text='Hour with most detections (0-23)', null=True),
        ),
        migrations.AddField(
            model_name='detectionanalytics',
            name='suspicious_objects_list',
            field=models.TextField(default='[]', help_text='JSON: list of suspicious objects detected'),
        ),
        migrations.AddField(
            model_name='detectionanalytics',
            name='unique_objects',
            field=models.IntegerField(default=0, help_text='Number of unique object classes'),
        ),
        migrations.AlterField(
            model_name='detectionanalytics',
            name='period_end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='detectionanalytics',
            name='period_start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
