# Generated by Django 5.2.7 on 2025-10-29 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_detectionanalytics_anomaly_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('security', 'Security'), ('optimization', 'Optimization'), ('behavior', 'Behavior Analysis'), ('alert', 'Alert Management'), ('monitoring', 'Monitoring Enhancement')], max_length=20)),
                ('priority', models.IntegerField(choices=[(5, 'Critical'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'Info')], default=3)),
                ('impact', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action', models.TextField(help_text='Recommended action to take')),
                ('confidence', models.FloatField(default=0.0, help_text='AI confidence score (0-1)')),
                ('metadata', models.TextField(default='{}', help_text='JSON: additional context and data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('acted', 'Acted Upon'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this recommendation expires', null=True)),
                ('user_feedback', models.TextField(blank=True, help_text="User's feedback on this recommendation")),
                ('was_helpful', models.BooleanField(blank=True, help_text='User rating: was this helpful?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'ordering': ['-priority', '-confidence', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'priority'], name='analytics_a_user_id_708cf9_idx'), models.Index(fields=['recommendation_type', 'priority'], name='analytics_a_recomme_840c56_idx'), models.Index(fields=['created_at', 'expires_at'], name='analytics_a_created_2adaa6_idx')],
            },
        ),
    ]
