# Generated by Django 4.2 on 2025-10-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouvment_detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectionevent',
            new_name='mouvment_de_timesta_e45e91_idx',
            old_name='detection_d_timesta_bff5ba_idx',
        ),
        migrations.RenameIndex(
            model_name='detectionevent',
            new_name='mouvment_de_detecti_3262ac_idx',
            old_name='detection_d_detecti_dc4314_idx',
        ),
    ]
