# Generated by Django 5.2.7 on 2025-10-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='anomaly_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='method',
            field=models.CharField(choices=[('password', 'password'), ('face', 'face'), ('ai', 'ai')], default='password', max_length=20),
        ),
    ]
