# Generated by Django 5.2.7 on 2025-10-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Main command text', max_length=100, unique=True)),
                ('synonyms', models.TextField(blank=True, help_text='Comma-separated synonyms')),
                ('enabled', models.BooleanField(default=True, help_text='Is this command active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
