# Generated by Django 5.2.7 on 2025-10-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notifications.notificationpreference',),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='min_severity_push',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS notifications (E.164 format: +33612345678)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='phone_verification_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Whether phone number has been verified'),
        ),
        migrations.CreateModel(
            name='SMSDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('sms_provider', models.CharField(choices=[('twilio', 'Twilio'), ('other', 'Other')], default='twilio', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Delivery Log',
                'verbose_name_plural': 'SMS Delivery Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_9c80cd_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_7b5f61_idx'), models.Index(fields=['provider_message_id'], name='notificatio_provide_c58c2a_idx')],
            },
        ),
    ]
